#if RETRO_REV02
#define CHECK_STAT(statName, achievementName, maxVal) if (!strcmp(stat->name, #statName) && *(int *)stat->data == maxVal) \
{ \
    SKU::AchievementID achievement; \
    achievement.identifier = #achievementName; \
    SKU::TryUnlockAchievement(&achievement); \
}

void EOSStats::TryTrackStat(StatInfo *stat)
{
    CHECK_STAT(DEFEAT_ENEMY,     ID_15_NOVICE_HERO, 50)
    CHECK_STAT(DEFEAT_ENEMY,     ID_29_HERO_FOR_ALL, 200)
    CHECK_STAT(DEFEAT_ENEMY_BY_SPIN_DASH, ID_14_DEFEAT_ENEMY_BY_SPIN_DASH, 200)
    CHECK_STAT(RING_COUNT,       ID_13_RING_COLLECTOR, 1000)
    CHECK_STAT(FLYING_COUNT,     ID_19_TAILS_FLYING, 1)
    CHECK_STAT(GLIDING_COUNT,    ID_18_KNUCKLES_GLIDING, 1)
    CHECK_STAT(WATCH_OPENING2,   ID_04_SONIC3K_WATCH_OPENING, 1)
    CHECK_STAT(CLEAR_ALL_STAGE2, ID_34_SONIC3K_CLEAR_ALL_STAGE, 1)
    CHECK_STAT(TRANSFORM_SUPER_SONIC_COUNT, ID_30_TRANSFORM_SUPER_SONIC, 1)
    CHECK_STAT(DEFEAT_RHINOBOT,  ID_11_SONIC3K_DEFEAT_RHINOBOT, 10)
    CHECK_STAT(GET_BARRIER_KIND, ID_12_SONIC3K_GET_ALL_BARRIERS, 3)
}
#endif